plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

title: "Globasa-Xwexi"
description: "Series of lessons for Globasa language, translated into several languages"
baseurl: "/globasa-xwexi-pages"
repository: "salif/globasa-xwexi-pages"
lang: en

author:
  name: "Salif Mehmed"
  url: "https://salif.eu"

social:
  name: "Globasa-Xwexi"
  links:
    - https://bsky.app/profile/globasa.salif.eu

defaults:
  - scope:
      path: ""
    values:
      image: "assets/Globasa-Xwexi-1000.png"
  - scope:
      path: "*.bul.md"
    values:
      lang: "bg"
      description: "Научете глобаса, новосъздаден, истински международен спомагателен език."
  - scope:
      path: "*.eng.md"
    values:
      lang: "en"
      description: "Learn Globasa, a newly constructed, truly international auxiliary language."
  - scope:
      path: "*.spa.md"
    values:
      lang: "es"
  - scope:
      path: "*.epo.md"
    values:
      lang: "eo"
  - scope:
      path: "*.fra.md"
    values:
      lang: "fr"
  - scope:
      path: "*.rus.md"
    values:
      lang: "ru"
      description: "Изучайте глобаса, новый плановый и по-настоящему международный язык общения."
