plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

title: "globasa-xwexi"
description: "Series of lessons and a complete grammar for Globasa, including Bulgarian translation."
repository: salif/globasa-xwexi-pages

defaults:
  - scope:
      path: "*.bul.md"
    values:
      lang: "bg"
  - scope:
      path: "*.eng.md"
    values:
      lang: "en"
  - scope:
      path: "*.spa.md"
    values:
      lang: "es"
  - scope:
      path: "*.epo.md"
    values:
      lang: "eo"
  - scope:
      path: "*.fra.md"
    values:
      lang: "fr"
