plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - Home.md

title: "globasa-xwexi"
description: "Series of lessons for Globasa language, including Bulgarian translation."
baseurl: "/globasa-xwexi-pages"
repository: salif/globasa-xwexi-pages

defaults:
  - scope:
      path: "*.bul.md"
    values:
      lang: "bg"
  - scope:
      path: "*.eng.md"
    values:
      lang: "en"
  - scope:
      path: "*.spa.md"
    values:
      lang: "es"
  - scope:
      path: "*.epo.md"
    values:
      lang: "eo"
  - scope:
      path: "*.fra.md"
    values:
      lang: "fr"
  - scope:
      path: "*.rus.md"
    values:
      lang: "ru"
