plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .git/
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - Gemfile
  - Gemfile.lock

title: "Globasa-Xwexi"
description: "Series of lessons for Globasa language, translated into several languages"
baseurl: "/globasa-xwexi-pages"
repository: "salif/globasa-xwexi-pages"
lang: en

author:
  name: "Salif Mehmed"
  url: "https://salif.eu"

social:
  name: "Globasa-Xwexi"
  links:
    - https://bsky.app/profile/globasa.salif.eu

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      image: "assets/Globasa-Xwexi-1000.png"
  - scope:
      path: "./*.eng.md"
      type: "pages"
    values:
      lang: "en"
  - scope:
      path: "./*.spa.md"
      type: "pages"
    values:
      lang: "es"
