plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .git/
  - .sass-cache/
  - .jekyll-cache/
  - .bundle/
  - Gemfile
  - Gemfile.lock

title: "Globasa-Xwexi"
description: "Series of lessons for Globasa language, translated into several languages"
baseurl: "/globasa-xwexi-pages"
repository: "salif/globasa-xwexi-pages"
lang: en

author: salif

social:
  name: "Globasa-Xwexi"
  links:
    - https://bsky.app/profile/globasa.salif.eu

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      image: "assets/icon-1000x1000.png"
